#!/bin/bash

# Get bootstrap script
cd /tmp
git clone https://github.com/shott85/cjp-aws-cjoc-bootstrap
chmod +x /tmp/cjp-aws-cjoc-bootstrap/bootstrap.sh

# Execute it
/tmp/cjp-aws-cjoc-bootstrap/bootstrap.sh

# Remove the script remnants
rm -rf /tmp/cjp-aws-cjoc-bootstrap
